=== 2lambda123/airbyte/airbyte-integrations/connectors/source-lexoffice/source_lexware/schemas/voucher_list.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "voucherType": {
            "type": "string"
        },
        "voucherStatus": {
            "type": "string"
        },
        "voucherNumber": {
            "type": "string"
        },
        "voucherDate": {
            "type": "string",
            "format": "date-time"
        },
        "createdDate": {
            "type": "string",
            "format": "date-time"
        },
        "updatedDate": {
            "type": "string",
            "format": "date-time"
        },
        "dueDate": {
            "type": "string",
            "format": "date-time"
        },
        "contactId": {
            "type": "string"
        },
        "contactName": {
            "type": "string"
        },
        "totalAmount": {
            "type": "number"
        },
        "openAmount": {
            "type": "number"
        },
        "currency": {
            "type": "string"
        },
        "archived": {
            "type": "boolean"
        }
    },
    "required": [
        "id",
        "voucherType",
        "voucherStatus",
        "voucherNumber",
        "voucherDate",
        "createdDate",
        "updatedDate",
        "archived"
    ]
}

=== 2lambda123/airbyte/airbyte-integrations/connectors/source-lexoffice/integration_tests/sample_result.json
{
    "id": "b4d19a38-aab9-4420-a607-948d48b6640b",
    "voucherType": "purchaseinvoice",
    "voucherStatus": "overdue",
    "voucherNumber": "lx2022090067793",
    "voucherDate": "2022-09-11T00:00:00.000+02:00",
    "createdDate": "2022-09-11T04:21:36.000+02:00",
    "updatedDate": "2022-09-11T04:21:36.000+02:00",
    "dueDate": "2022-09-16T00:00:00.000+02:00",
    "contactId": "dd19ef5b-f78b-4333-8f34-279de896a3cf",
    "contactName": "Haufe Service Center GmbH",
    "totalAmount": 22.49,
    "openAmount": 22.49,
    "currency": "EUR",
    "archived": false
}
